### ISSUE TITLE
Unable to compute calibration from recorded bag.

### ISSUE THREAD

**Issue by SimbaXu** [YoshuaNava/ridgeback#1]
Hi, when I tried to do IMU calibration, I got the message "Unable to compute calibration from recorded bag.". Please advice upon this issue. Thanks!

**Comment by diogoalmeida** [comment]
Can you add more information to the issue? What commands are you running and what is the output?

**Comment by anirvan95** [comment]
Hello, I am facing the same issue. On executing the compass calibration it exists without completing with error unable to compute calibration from recorded bag. I have attached screenshots for more information 
![error_calibrating](https://user-images.githubusercontent.com/32486293/54443514-07c04c00-4741-11e9-9882-f4c0f45e5ba8.png)
![Error_saving_file](https://user-images.githubusercontent.com/32486293/54443515-07c04c00-4741-11e9-81fb-e83016cc06c9.png)

**Comment by diogoalmeida** [comment]
Please use the github markdown instead of screenshots when posting commands and the resulting output. Makes it easier for others to try to replicate your example. For instance, you can post the command you executed as

``
$ rosrun ridgeback_base calibrate_compass
``

Otherwise, this looks like the `compute_calibration` node that is installed on ridgeback is expecting a different type of message than what its getting. What's the content of the `imu_record.bag` file you got?

**Comment by anirvan95** [comment]
Sorry for the screenshot, I will follow your suggestions from here on. The `imu_record.bag` file recorded `/imu/data_raw` and `/imu/mag`. The `/imu/mag` is of type `sensor_msgs/MagneticField` and somehow the `compute_calibration` node is trying to access incompatible vector field. Any suggestions ? I have attached the bag files for your reference. 
[imu_record.bag.zip](https://github.com/kth-ros-pkg/ridgeback/files/2978177/imu_record.bag.zip)

**Comment by diogoalmeida** [comment]
Hmmm. The `compute_calibration` code can be found [here](https://github.com/ridgeback/ridgeback_robot/blob/indigo-devel/ridgeback_base/scripts/compute_calibration) for the indigo version. If you look at line 42, it seems to indeed look for a `vector` field on the /imu/mag message, which does not exist. 

I'd recommend you to open an issue on ridgeback's repository to see if someone from clearpath can assist you with this problem. 

PS: You might also try to just edit the script in `/opt/ros/indigo/lib/ridgeback_base/compute_calibration` and change line 42 to use `.magnetic_field` instead of `.vector`. If you do this and it works, I'd still strongly encourage you to open an issue in the ridgeback repo.

**Comment by anirvan95** [comment]
Ok, thank you. I was able to make small change in the code and compute the calibration. I will open the issue in the ridgeback repo as suggested.
